config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :members
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
	validates :name,
	  presence: true

	validates :phone,
	  presence: true,
	  format: {with: /\A[0-9-]{,14}\z/}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    #検索
    @members = Member.order :yomi
  end
  
  def show
    @member = find_member_by_id
  end

  def new
    #Memberクラス作成
    @member = Member.new
  end
  
  def create
    @member = Member.new(member_params)
    if @member.save
      #登録成功
      redirect_to_by(path: members_path, message: "#{@member.name}の連絡先を登録しました")
    else
      #登録失敗
      render action: :new
    end
  end
  
  def edit
    #条件付き検索
    @member = find_member_by_id
  end
  
  def update
    #条件付き検索
    @member = find_member_by_id
    #更新処理
    if @member.update(member_params)
      #更新成功
      redirect_to_by(path: members_path, message: "#{@member.name}の連絡先を更新しました")
    else
      #更新失敗
      render action: :edit
    end
  end
  
  def destroy
    #条件付き検索
    @member = find_member_by_id
    #削除
    @member.destroy
    redirect_to_by(path: members_path, message: "#{@member.name}の連絡先を削除しました")
  end
  
  private
  def member_params
    params.require(:member).permit(:name, :yomi, :phone)
  end
  
  def find_member_by_id
    Member.find(params[:id])
  end

  def redirect_to_by(path:, message:)
    redirect_to path, notice: message

    # redirect_to だと第二引数はnotice:, alert:を指定できる
    # それ以外を指定する場合　redirect_to path, flash: {key: "message"}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhoneBook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_for @member do |f| %>
  <% if @member.errors.any? %>
    <h3>入力した内容にエラーが<%= @member.errors.count %>件あります</h3>
      <ul>
      <% @member.errors.full_messages.each do | message | %>
        <li><%= message %></li>
      <% end %>
      </ul>
  <% end %>
  <p>
  <%= f.label :name %>
  <%= f.text_field :name %>
  </p>
  
  <p>
  <%= f.label :yomi %>
  <%= f.text_field :yomi %>
  </p>
  
  <p>
  <%= f.label :phone %>
  <%= f.text_field :phone %>
  </p>
  
  <% if @member.id %>
    <%= f.submit "修正" %>
  <% else %>
    <%= f.submit "登録" %>
  <% end %>
<% end %>

app/views/members/edit.html.erb
<h2>修正</h2>
 
<%= render "form" %>

<%= link_to "削除", member_path(@member.id), method: :delete, data: {confirm: "本当に削除しますか？"} %>
<%= link_to "戻る", members_path %>

app/views/members/index.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<% @members.each do | member | %>
  <div class="member">
    <p><%= link_to member.name, member_path(member.id) %></p>
    <p><%= member.yomi %></p>
    <p><%= member.phone %></p>
  </div>
<% end %>


<%= link_to "新規登録", new_member_path %>

app/views/members/new.html.erb
<h2>新規登録</h2>
 
<%= render "form" %>

<%= link_to "戻る", members_path %>

app/views/members/show.html.erb
<%= form_for @member do |f| %>
  <p>
  <%= f.label :name %>
  <%= @member.name %>
  </p>
  
  <p>
  <%= f.label :yomi %>
  <%= @member.yomi %>
  </p>
  
  <p>
  <%= f.label :phone %>
  <%= @member.phone %>
  </p>
  <%= link_to "修正", edit_member_path(@member.id) %>
  <%= link_to "戻る", members_path %>
<% end %>